#!/usr/bin/env bash

watch_dir="/tmp/testdir"

inotifywait -m -e close_write -e moved_to --format "%f" "$watch_dir" | while
read -r filename; do
    if [[ -f "$watch_dir/$filename" ]]; then   
    echo "$filename"    

    ext="${filename##*.}"
    ext="${ext,,}"
    echo "$ext"

    case "$ext" in
        jpg|jpeg|png|webp)      dest="image_files" ;;
        pptx|pdf|docx)          dest="document_files" ;;
        xlsx|csv|json)          dest="data_files" ;; 
        mp4|mp3|mov)            dest="media_files" ;; 
        txt)                    dest="txt_files" ;;
        *)                      dest="other_files" ;; 
    esac

    mkdir -p "$watch_dir/$dest"

    mv "$watch_dir/$filename" "$watch_dir/$dest/"
    echo "$filename was moved into $dest"

    fi  
done
