#!/usr/bin/env bash

WATCH_DIR="$HOME/Downloads"

inotifywait -m -e close_write -e moved_to --format "%f" "$WATCH_DIR" | while
read -r filename; do
    if [[ -f "$WATCH_DIR/$filename" ]]; then   
        echo "$filename"    

        ext="${filename##*.}"
        ext="${ext,,}"

        case "$ext" in
            jpg|jpeg|png|webp)      dest="image_files" ;;
            pptx|pdf|docx)          dest="document_files" ;;
            xlsx|csv|json)          dest="data_files" ;; 
            mp4|mp3|mov)            dest="media_files" ;; 
            txt)                    dest="txt_files" ;;
            *)                      dest="other_files" ;; 
        esac

        mkdir -p "$WATCH_DIR/$dest"

        mv "$WATCH_DIR/$filename" "$WATCH_DIR/$dest/"
        echo "$filename was moved into $dest"

    fi  
done
